version: "3.9"
services:
  resource-service:
    build: .
    image: sergeiavdeev/schedule-service:${TAG}
    container_name: schedule-service
    command: java -jar schedule-service-0.0.1-SNAPSHOT.jar
    restart: always
    environment:
      spring.profiles.active: ${PROFILE}
    networks:
      - ttc-tops
    deploy:
      resources:
        limits:
          memory: '512M'
        reservations:
          memory: '256M'
networks:
  ttc-tops:
    external: true
    name: ttc-tops
    driver: bridge


