spring:
  application:
    name: schedule-service
  config:
    import: configserver:http://config-server:8888
  cloud:
    config:
      fail-fast: true
keycloak:
  uri: https://avdeev-sa.ru/keycloak
  realm: ttc-tops
  username: admin
  password: 61Ifhjukjn
  clientId: admin-cli
